spring.application.name=zorvyn
server.port=9091
# === Database Configuration ===
#spring.datasource.url=jdbc:mysql://localhost:3306/zorvyn_banking_app
#spring.datasource.username=root
#spring.datasource.password=Rohan@721422
spring.datasource.url=jdbc:mysql://localhost:3306/zorvyn_banking_app?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rohan@721422

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

## === Connection Pool (Optional: HikariCP is default) ===
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
spring.mvc.pathmatch.matching-strategy=ant_path_matcher